# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Qiu/Desktop/codlab/work/vivado/constraints/Nexys4DDR_CPU.xdc

# IP: ip/imem/imem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imem || ORIG_REF_NAME==imem}]
